
export const FETCH_SECONDHANDPRODUCTS_REQUEST = "FETCH_SECONDHANDPRODUCTS_REQUEST";
export const FETCH_SECONDHANDPRODUCTS_SUCCESS = "FETCH_SECONDHANDPRODUCTS_SUCCESS";
export const FETCH_SECONDHANDPRODUCTS_FAIL = "FETCH_SECONDHANDPRODUCTS_FAIL";

export const DELETE_SECONDHANDPRODUCT_REQUEST = "DELETE_SECONDHANDPRODUCT_REQUEST";
export const DELETE_SECONDHANDPRODUCT_SUCCESS = "DELETE_SECONDHANDPRODUCT_SUCCESS";
export const DELETE_SECONDHANDPRODUCT_FAIL = "DELETE_SECONDHANDPRODUCT_FAIL";

export const EDIT_SECONDHANDPRODUCT_REQUEST = "EDIT_SECONDHANDPRODUCT_REQUEST";
export const EDIT_SECONDHANDPRODUCT_SUCCESS = "EDIT_SECONDHANDPRODUCT_SUCCESS";
export const EDIT_SECONDHANDPRODUCT_FAIL = "EDIT_SECONDHANDPRODUCT_FAIL";

export const ADD_SECONDHANDPRODUCT_REQUEST = "ADD_SECONDHANDPRODUCT_REQUEST";
export const ADD_SECONDHANDPRODUCT_SUCCESS = "ADD_SECONDHANDPRODUCT_SUCCESS";
export const ADD_SECONDHANDPRODUCT_FAIL = "ADD_SECONDHANDPRODUCT_FAIL";