
export const FETCH_SUBCATEGORIES_REQUEST = "FETCH_SUBCATEGORIES_REQUEST";
export const FETCH_SUBCATEGORIES_SUCCESS = "FETCH_SUBCATEGORIES_SUCCESS";
export const FETCH_SUBCATEGORIES_FAIL = "FETCH_SUBCATEGORIES_FAIL";

export const DELETE_SUBCATEGORY_REQUEST = "DELETE_SUBCATEGORY_REQUEST";
export const DELETE_SUBCATEGORY_SUCCESS = "DELETE_SUBCATEGORY_SUCCESS";
export const DELETE_SUBCATEGORY_FAIL = "DELETE_SUBCATEGORY_FAIL";

export const EDIT_SUBCATEGORY_REQUEST = "EDIT_SUBCATEGORY_REQUEST";
export const EDIT_SUBCATEGORY_SUCCESS = "EDIT_SUBCATEGORY_SUCCESS";
export const EDIT_SUBCATEGORY_FAIL = "EDIT_SUBCATEGORY_FAIL";

export const ADD_SUBCATEGORY_REQUEST = "ADD_SUBCATEGORY_REQUEST";
export const ADD_SUBCATEGORY_SUCCESS = "ADD_SUBCATEGORY_SUCCESS";
export const ADD_SUBCATEGORY_FAIL = "ADD_SUBCATEGORY_FAIL";