
export const FETCH_COLOURS_REQUEST = "FETCH_COLOURS_REQUEST";
export const FETCH_COLOURS_SUCCESS = "FETCH_COLOURS_SUCCESS";
export const FETCH_COLOURS_FAIL = "FETCH_COLOURS_FAIL";

export const DELETE_COLOUR_REQUEST = "DELETE_COLOUR_REQUEST";
export const DELETE_COLOUR_SUCCESS = "DELETE_COLOUR_SUCCESS";
export const DELETE_COLOUR_FAIL = "DELETE_COLOUR_FAIL";

export const EDIT_COLOUR_REQUEST = "EDIT_COLOUR_REQUEST";
export const EDIT_COLOUR_SUCCESS = "EDIT_COLOUR_SUCCESS";
export const EDIT_COLOUR_FAIL = "EDIT_COLOUR_FAIL";

export const ADD_COLOUR_REQUEST = "ADD_COLOUR_REQUEST";
export const ADD_COLOUR_SUCCESS = "ADD_COLOUR_SUCCESS";
export const ADD_COLOUR_FAIL = "ADD_COLOUR_FAIL";