
export const FETCH_PRODUCTIMAGES_REQUEST = "FETCH_PRODUCTIMAGES_REQUEST";
export const FETCH_PRODUCTIMAGES_SUCCESS = "FETCH_PRODUCTIMAGES_SUCCESS";
export const FETCH_PRODUCTIMAGES_FAIL = "FETCH_PRODUCTIMAGES_FAIL";

export const DELETE_PRODUCTIMAGE_REQUEST = "DELETE_PRODUCTIMAGE_REQUEST";
export const DELETE_PRODUCTIMAGE_SUCCESS = "DELETE_PRODUCTIMAGE_SUCCESS";
export const DELETE_PRODUCTIMAGE_FAIL = "DELETE_PRODUCTIMAGE_FAIL";

export const EDIT_PRODUCTIMAGE_REQUEST = "EDIT_PRODUCTIMAGE_REQUEST";
export const EDIT_PRODUCTIMAGE_SUCCESS = "EDIT_PRODUCTIMAGE_SUCCESS";
export const EDIT_PRODUCTIMAGE_FAIL = "EDIT_PRODUCTIMAGE_FAIL";

export const ADD_PRODUCTIMAGE_REQUEST = "ADD_PRODUCTIMAGE_REQUEST";
export const ADD_PRODUCTIMAGE_SUCCESS = "ADD_PRODUCTIMAGE_SUCCESS";
export const ADD_PRODUCTIMAGE_FAIL = "ADD_PRODUCTIMAGE_FAIL";