
export const FETCH_BRENDS_REQUEST = "FETCH_BRENDS_REQUEST";
export const FETCH_BRENDS_SUCCESS = "FETCH_BRENDS_SUCCESS";
export const FETCH_BRENDS_FAIL = "FETCH_BRENDS_FAIL";

export const DELETE_BREND_REQUEST = "DELETE_BREND_REQUEST";
export const DELETE_BREND_SUCCESS = "DELETE_BREND_SUCCESS";
export const DELETE_BREND_FAIL = "DELETE_BREND_FAIL";

export const EDIT_BREND_REQUEST = "EDIT_BREND_REQUEST";
export const EDIT_BREND_SUCCESS = "EDIT_BREND_SUCCESS";
export const EDIT_BREND_FAIL = "EDIT_BREND_FAIL";

export const ADD_BREND_REQUEST = "ADD_BREND_REQUEST";
export const ADD_BREND_SUCCESS = "ADD_BREND_SUCCESS";
export const ADD_BREND_FAIL = "ADD_BREND_FAIL";