
export const FETCH_MATERIALS_REQUEST = "FETCH_MATERIALS_REQUEST";
export const FETCH_MATERIALS_SUCCESS = "FETCH_MATERIALS_SUCCESS";
export const FETCH_MATERIALS_FAIL = "FETCH_MATERIALS_FAIL";

export const DELETE_MATERIAL_REQUEST = "DELETE_MATERIAL_REQUEST";
export const DELETE_MATERIAL_SUCCESS = "DELETE_MATERIAL_SUCCESS";
export const DELETE_MATERIAL_FAIL = "DELETE_MATERIAL_FAIL";

export const EDIT_MATERIAL_REQUEST = "EDIT_MATERIAL_REQUEST";
export const EDIT_MATERIAL_SUCCESS = "EDIT_MATERIAL_SUCCESS";
export const EDIT_MATERIAL_FAIL = "EDIT_MATERIAL_FAIL";

export const ADD_MATERIAL_REQUEST = "ADD_MATERIAL_REQUEST";
export const ADD_MATERIAL_SUCCESS = "ADD_MATERIAL_SUCCESS";
export const ADD_MATERIAL_FAIL = "ADD_MATERIAL_FAIL";