
export const FETCH_SIZES_REQUEST = "FETCH_SIZES_REQUEST";
export const FETCH_SIZES_SUCCESS = "FETCH_SIZES_SUCCESS";
export const FETCH_SIZES_FAIL = "FETCH_SIZES_FAIL";

export const DELETE_SIZE_REQUEST = "DELETE_SIZE_REQUEST";
export const DELETE_SIZE_SUCCESS = "DELETE_SIZE_SUCCESS";
export const DELETE_SIZE_FAIL = "DELETE_SIZE_FAIL";

export const EDIT_SIZE_REQUEST = "EDIT_SIZE_REQUEST";
export const EDIT_SIZE_SUCCESS = "EDIT_SIZE_SUCCESS";
export const EDIT_SIZE_FAIL = "EDIT_SIZE_FAIL";

export const ADD_SIZE_REQUEST = "ADD_SIZE_REQUEST";
export const ADD_SIZE_SUCCESS = "ADD_SIZE_SUCCESS";
export const ADD_SIZE_FAIL = "ADD_SIZE_FAIL";